import { MovingTask } from '../../types';

export const MOVING_TASKS: MovingTask[] = [
  {
    id: 'moving-1',
    title: 'Create a moving budget',
    description: 'Calculate all moving costs including movers, supplies, insurance, and travel',
    timeline: '8 weeks before',
    category: 'planning',
  },
  {
    id: 'moving-2',
    title: 'Research and book moving company',
    description: 'Get quotes from 3+ companies, check reviews, confirm insurance coverage',
    timeline: '6-8 weeks before',
    category: 'logistics',
  },
  {
    id: 'moving-3',
    title: 'Order moving supplies',
    description: 'Boxes, tape, bubble wrap, markers, furniture covers, and labels',
    timeline: '6 weeks before',
    category: 'logistics',
  },
  {
    id: 'moving-4',
    title: 'Start decluttering and downsizing',
    description: 'Donate, sell, or discard items you no longer need',
    timeline: '6 weeks before',
    category: 'planning',
  },
  {
    id: 'moving-5',
    title: 'Notify landlord (if renting)',
    description: 'Provide proper notice as per lease agreement, typically 60 days',
    timeline: '6 weeks before',
    category: 'planning',
  },
  {
    id: 'moving-6',
    title: 'Submit change of address',
    description: 'Update address with Canada Post, banks, CRA, Service Ontario, and employers',
    timeline: '4 weeks before',
    category: 'utilities',
  },
  {
    id: 'moving-7',
    title: 'Transfer or set up utilities',
    description: 'Arrange electricity, gas, water, internet, and cable for move-in date',
    timeline: '4 weeks before',
    category: 'utilities',
  },
  {
    id: 'moving-8',
    title: 'Update insurance policies',
    description: 'Transfer home insurance, update auto insurance with new address',
    timeline: '3-4 weeks before',
    category: 'utilities',
  },
  {
    id: 'moving-9',
    title: 'Arrange time off work',
    description: 'Book vacation days for moving day and settling in',
    timeline: '3 weeks before',
    category: 'planning',
  },
  {
    id: 'moving-10',
    title: 'Start packing non-essentials',
    description: 'Pack seasonal items, decorations, books, and rarely used belongings',
    timeline: '3 weeks before',
    category: 'logistics',
  },
  {
    id: 'moving-11',
    title: 'Update medical records and prescriptions',
    description: 'Transfer prescriptions, notify doctors and dentists, request medical records',
    timeline: '2-3 weeks before',
    category: 'utilities',
  },
  {
    id: 'moving-12',
    title: 'Arrange school transfers (if applicable)',
    description: 'Register children at new schools, transfer records, arrange transportation',
    timeline: '2-3 weeks before',
    category: 'utilities',
  },
  {
    id: 'moving-13',
    title: 'Deep clean current home',
    description: 'Schedule professional cleaning or plan DIY cleaning schedule',
    timeline: '2 weeks before',
    category: 'final-prep',
  },
  {
    id: 'moving-14',
    title: 'Confirm moving arrangements',
    description: 'Reconfirm date, time, and details with moving company',
    timeline: '1 week before',
    category: 'logistics',
  },
  {
    id: 'moving-15',
    title: 'Pack essentials box',
    description: 'Toiletries, medications, chargers, important documents, change of clothes',
    timeline: '1 week before',
    category: 'logistics',
  },
  {
    id: 'moving-16',
    title: 'Defrost and clean appliances',
    description: 'Empty, defrost, and clean refrigerator and freezer 24-48 hours before',
    timeline: '2 days before',
    category: 'final-prep',
  },
  {
    id: 'moving-17',
    title: 'Do final walkthrough of old home',
    description: 'Check all rooms, closets, basement, garage, and outdoor spaces',
    timeline: 'Moving day',
    category: 'final-prep',
  },
  {
    id: 'moving-18',
    title: 'Supervise movers and inventory',
    description: 'Check items as they\'re loaded, keep inventory list, take photos if needed',
    timeline: 'Moving day',
    category: 'logistics',
  },
  {
    id: 'moving-19',
    title: 'Inspect and unpack essentials at new home',
    description: 'Check for damage, test utilities, unpack first-night essentials',
    timeline: 'Moving day',
    category: 'final-prep',
  },
];

export const TOTAL_TASKS = MOVING_TASKS.length;
